info:
  description: 2222 Finally Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
foo: arnold

mainDBConnectionString: "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=MainDB;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
AutoSmart:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=AutoSmart;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
Main:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=Main;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
Item: "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=Item;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
ItemSearch: "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=ItemSearch;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
Vendor:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=Vendor;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
InventoryLog:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=InventoryLog;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
Logging:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=Logging;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
CUDLDiag:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=CUDLDiag;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
CUDLDiag.Database.Connection:  "Data Source=np-amsql-smi.1afdecf481e7.database.windows.net,1433; Initial Catalog=CudlDiag;User ID=amsql_NonProd_SA;Password=xcYVwax60qbmkMgLGsGD"
DealerPortal: DealerPortalDB
AutoSmartReporting: AutoSmartReportingDB

Toolkit.SsoAccount.Url: Toolkit.SsoAccount.Url
Toolkit.SsoDomainManual.Url: Toolkit.SsoDomainManual.Url
Toolkit.SsoApplication.Url: Toolkit.SsoApplication.Url
Toolkit.SsoDomainWindows.Url: Toolkit.SsoDomainWindows.Url
ServiceAccount.Name: ServiceAccount.Name
ServiceAccount.Password: ServiceAccount.Password
Security.Admin.svc.URL: Security.Admin.svc.URL
ActionLoggingAPIURL: ActionLoggingAPIURL
AutoSmartClientsAPIUrl: AutoSmartClientsAPIUrl
CreditUnionAPIURL: CreditUnionAPIURL
CreditUnionApiUrlVS2: CreditUnionApiUrlVS2
DealerAPIURLVS2: DealerAPIURLVS2
AutoSmartSystemTypesAPIURL: AutoSmartSystemTypesAPIURL
AutoSmartInventoryAPIUrl: AutoSmartInventoryAPIUrl
AutoSmartReportingAPIUrl: AutoSmartReportingAPIUrl
HealthStatusPostUrl: HealthStatusPostUrl
Partner.DealerRater.Access.Token: Partner.DealerRater.Access.Token
Partner.DealerRater.Url: Partner.DealerRater.Url
