info:
  description: 2222 Finally Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
foo: arnold
mainDBConnectionString: FROM APPlication.yml file Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;